#!/usr/bin/env zsh

source macos

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  echo "removing $folder"
  stow -D $folder
done
