#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

# link wholesale
for f in `find . -regex ".*\.vim$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/dotfiles/TheWawan/$f ~/.config/nvim/$f
done

rm -rf ~/.tmux.conf
ln -s ~/dotfiles/TheWawan/tmux.conf ~/.tmux.conf

