#!/usr/bin/env bash
source ./bin/core/env

if [ ! -d "$HOME/.oh-my-zsh" ]; then
	source ./bin/core/deps-scripts/install-zsh
fi

source ./bin/core/env
source ./bin/core/deps-scripts/install-all
source ./bin/core/setup-env
