#!/usr/bin/env bash

function displayHelp() {
  echo "Usage: nvim-env [options]"
  echo "Options:"
  echo "  --default      Load default nvim environment"
  echo "  --playground   Load playground nvim environment"
  echo "  -h, --help     Display this help message"
}

while [ "$#" -gt 0 ]; do
  curr=$1
  shift

  case "$curr" in
    "--default")
      mv ~/.config/nvim{,.bak.playground}
      mv ~/.local/share/nvim{,.bak.playground}
      mv ~/.local/state/nvim{,.bak.playground}
      mv ~/.cache/nvim{,.bak.playground}

      mv ~/.config/nvim{.bak.default,}
      mv ~/.local/share/nvim{.bak.default,}
      mv ~/.local/state/nvim{.bak.default,}
      mv ~/.cache/nvim{.bak.default,}
      ;;
    "--playground")
      mv ~/.config/nvim{,.bak.default}
      mv ~/.local/share/nvim{,.bak.default}
      mv ~/.local/state/nvim{,.bak.default}
      mv ~/.cache/nvim{,.bak.default}

      mv ~/.config/nvim{.bak.playground,}
      mv ~/.local/share/nvim{.bak.playground,}
      mv ~/.local/state/nvim{.bak.playground,}
      mv ~/.cache/nvim{.bak.playground,}
      echo "playground loaded"
      ;;
    "--help")
      displayHelp
      ;;
    "-h")
      displayHelp
      ;;
      *) echo "Unavailable command... $curr" ;;
    esac
  done
