#!/usr/bin/env bash

NVIM="~/nvim-macos/bin/nvim ."
DOCKER_COMPOSE_UP="docker-compose up"
DOCKER_ENV="~/Lab/docker-env"
CONFIG="~/.config/nvim"
LAB="~/Lab"

createWindow() {
    session=$1
    window=$2
    shift
    shift
    hasWindow=$(tmux list-windows -t $session | grep "$window")
    if [ -z "$hasWindow" ]; then
        cmd="tmux -f ~/.config/nvim/tmux.conf neww -t $session: -n $window -d"
        if [ $# -gt 0 ]; then
            cmd="$cmd $@"
        fi
        echo "Creating Window(\"$hasWindow\"): $cmd"
        eval $cmd
    fi
}

createSession() {
    session=$1
    window=$2
    shift
    shift
    cmd="tmux new -f ~/.config/nvim/tmux.conf -s $session -d -n $window $@ > /dev/null 2>&1"

    echo "Creating Session: $cmd"
    eval $cmd
}

while [ "$#" -gt 0 ]; do
    curr=$1
    shift

    case "$curr" in
    "-config")
        createSession config primary
        createWindow config config -c $CONFIG "~/nvim-macos/bin/nvim ."
        ;;
    "-docker")
        createSession docker primary
        createWindow docker docker-env -c $DOCKER_ENV "~/nvim-macos/bin/nvim ."
        ;;
    "-random")
        createSession random primary
        createWindow random vim -c $LAB "~/nvim-macos/bin/nvim ."
        ;;
    "-playground")
        createSession playground primary
        ;;
    # Work in progress
    *) echo "Unavailable command... $curr"
    esac
done

